
server {
    listen 80;
    listen  [::]:80;
    ssi on;
    server_name localhost;

    root /opt/SJRJ/InG/var/www/html;
    index asm_index_redirect.php index.php index.html index.htm;
    client_body_temp_path  /opt/SJRJ/InG/tmp/logs/nginx 1 2;
    error_page 404  =200 /;

    include /opt/SJRJ/InG/etc/nginx/module/captive.conf;
    include /opt/SJRJ/InG/etc/nginx/module/access.conf;
    include /opt/SJRJ/InG/etc/nginx/module/compatible.conf;
    include /opt/SJRJ/InG/etc/nginx/module/ztpwss.conf;
    include /opt/SJRJ/InG/etc/nginx/module/outnet.conf;
}
