server {
    listen       [::]:44346 ssl;
    server_name  localhost;

    charset gbk;
    #ssl                  on;
    ssl_certificate      /opt/SJRJ/InG/etc/pki/tls/certs/localhost.crt;
    ssl_certificate_key  /opt/SJRJ/InG/etc/pki/tls/private/localhost.key;
    ssl_dhparam /opt/SJRJ/InG/etc/pki/tls/certs/dhparams.pem;

    root /opt/SJRJ/InG/var/www/html;
    index redirect.php;
    error_page 404  /redirect.php;
    error_page 403  /redirect.php;
    ssl_session_timeout  5m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    #ssl_protocols TLSv1;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers   on;

    location ~ \.(php)?$ 
    {
        fastcgi_index index.php;
        fastcgi_pass   fastcgi_backend;
        fastcgi_keep_conn on;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_ignore_client_abort on;
        include /opt/SJRJ/InG/etc/asm/nginx/*.conf;
        include fastcgi_params;
    }
}   
