user apache apache;
worker_processes  4;
worker_cpu_affinity 1000 0100 0010 0001;

#pid        logs/nginx.pid;

worker_rlimit_nofile 51200;
worker_shutdown_timeout 600s;

events {
	use epoll;
	worker_connections  51200;
}

http {
	include  mime.types;
	default_type  application/octet-stream;
	server_names_hash_bucket_size 128;
	client_header_buffer_size 4k;
	large_client_header_buffers 4 8k;
	client_max_body_size 2000m;
	client_body_buffer_size 256k;
	client_header_timeout 120;

	sendfile on;
	tcp_nopush on;
	fastcgi_intercept_errors on;

	server_tokens off;
	keepalive_timeout 10 10;
	proxy_buffer_size 4k;
	proxy_buffers 8 32k;
	proxy_busy_buffers_size 128k;
	proxy_temp_file_write_size 128k;

	gzip  on;
	gzip_min_length  1000;
	gzip_buffers     4 16k;
	gzip_proxied     expired no-cache no-store private auth;
	gzip_comp_level 9;
	gzip_types       text/plain text/css text/xml text/javascript application/x-javascript application/xml application/rss+xml application/xhtml+xml application/atom_xml;
	gzip_disable "MSIE [1-6].(?!.*SV1)";
	log_format  access  '$remote_addr - $remote_user [$time_local($msec)] "$request" '
		'$status $body_bytes_sent "$http_referer" '
		'"$http_user_agent" $http_x_forwarded_for';

	log_format weblog   '$remote_addr - $remote_user [$time_local($msec)] "$request" '
		       '$status $body_bytes_sent "$http_referer" '
		       '"$http_user_agent" $http_x_forwarded_for $request_time $upstream_response_time';
	error_log /opt/SJRJ/InG/tmp/logs/nginx/error.log  warn;
	access_log /opt/SJRJ/InG/tmp/logs/nginx/access.log weblog;

    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options nosniff;

	include vhost_dasm/*.conf;
}

