proxy_set_header Host $host;
proxy_set_header Client-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Server-Addr $server_addr;

proxy_set_header SERIAL_NUM $http_serial_num;
proxy_set_header ACCEPT $http_accept;
proxy_set_header SESSION-NUM $http_session_num;

