include /opt/SJRJ/InG/etc/nginx/common/host_limit.conf;

# Forbid access if there is no refer
location ^~ /tp/ {
    valid_referers server_names ~.;
    if ($invalid_referer) {
        return 403;
    }
}

location ^~ /access {
    charset gbk;
	set $is_exist_filename 1;

	if ($request_filename != '/opt/SJRJ/InG/var/www/html/access/index.php') {
		set $is_exist_filename 0;
	        rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
	}

	# else
	if ($is_exist_filename = 1) {
		root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
	}
	include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
}

location ^~ /source {
    charset gbk;
	rewrite ^(.*)$ $scheme://$http_host/access/ui/#/source/list permanent;
}
location ^~ /access/ui {
	charset utf-8;
	root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
}

location ^~ /client/ui {
        charset utf-8;
        root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
}

location ^~ /mobile/ui {
        charset utf-8;
        root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
}

location ^~ /client {
    charset utf-8;
}

location ^~ /download/soft/ {
    charset gbk;
	error_page 404 /404.html;
}
location ^~ /backend {
        charset gbk;
        alias  /opt/SJRJ/InG/var/www/admin.asm.com/public;
        try_files $uri $uri/ @backend;
        location ~ \.(php)?$ {
                fastcgi_index index.php;
                fastcgi_pass fastcgi_backend;
                fastcgi_keep_conn on;
                fastcgi_param  DOCUMENT_ROOT      $document_root;
                fastcgi_param SCRIPT_FILENAME $document_root/index.php;
                fastcgi_ignore_client_abort on;
                include /opt/SJRJ/InG/etc/asm/nginx/*.conf;
                include fastcgi_params;
        }
}

location @backend{
    charset gbk;
    rewrite /backend/(.*)$ /backend/index.php?/$1 last;
}
