include /etc/nginx/common/host_limit.conf;
location ^~ /access {
	set $is_exist_filename 1;

	if ($request_filename != '/var/www/html/access/index.php') {
		set $is_exist_filename 0;
	        rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
	}

	# else
	if ($is_exist_filename = 1) {
		root /var/www/access.asm.com/webroot;
	}
	include /etc/nginx/common/phpfpm.conf;
}

location ^~ /access/ui {
	charset utf-8;
	root /var/www/access.asm.com/webroot;
}

location ^~ /client/ui {
        charset utf-8;
        root /var/www/access.asm.com/webroot;
}

location ^~ /mobile/ui {
        charset utf-8;
        root /var/www/access.asm.com/webroot;
}

location ^~ /download/soft/ {
	error_page 404 /404.html;
}
