include /opt/SJRJ/InG/etc/nginx/common/host_limit.conf;
include /opt/SJRJ/InG/etc/nginx/module/dingtalk.conf;
include /opt/SJRJ/InG/etc/nginx/module/wework.conf;
include /opt/SJRJ/InG/etc/nginx/module/feishu.conf;

location = /backend_status {
    include /opt/SJRJ/InG/etc/nginx/common/phpfpm_backend.conf;
}

# Forbid access if there is no refer
location ^~ /tp/ {
    valid_referers server_names ~.;
    if ($invalid_referer) {
        return 403;
    }
}

location ^~ /backend {
	alias  /opt/SJRJ/InG/var/www/admin.asm.com/public;
    try_files $uri $uri/ @backend;
    location ~ \.(php)?$ {
            include /opt/SJRJ/InG/etc/nginx/common/phpfpm_admin.conf;
    }
}

location @backend{
    rewrite /backend/(.*)$ /backend/index.php?/$1 last;
}

location ^~ /admin{
	charset utf-8;
	if ($arg_frame = "SAMEORIGIN") {
		add_header X-Frame-Options SAMEORIGIN;
	}
	if ($arg_frame != "SAMEORIGIN") {
		add_header X-Frame-Options DENY;
	}


    #forbidden webpack sourcemap file request
    location ~* \.js\.map$ {
        if ($http_cookie !~* "debugsourcemap") {
                return 404;
        }
    }
}

location ^~ /tp/newHtml{
	charset utf-8;
}

location ^~ /download/ {
        location ~ \.php$ {
            return 404;
        }
 }


location ~ /vendor {
    deny all;
    return 403;
}

location ~* /composer\.(json|lock)$ {
    deny all;
    return 403;
}

location ^~ /phpdir {
    location ~ \.(php)?$ {
        include /opt/SJRJ/InG/etc/nginx/common/phpfpm_backend.conf;
    }
}

location ~ \.(php)?$ {
    #allow 127.0.0.1;
    #include /opt/SJRJ/InG/etc/allow.conf;
    #deny all;
    include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
}

location ^~ /access {
    rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
    location ^~ /access/index.php {
        root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
        include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
    }
}

location /wss {
    proxy_pass http://127.0.0.1:10000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    keepalive_timeout 70;
    proxy_connect_timeout 4s;
    proxy_read_timeout 180s;
    proxy_send_timeout 12s;
}

include /opt/SJRJ/InG/etc/nginx/module/admin_compatible.conf;
