location ^~ /asmmonitor{
    alias  /opt/SJRJ/InG/var/www/admin.asm.com/public;
    rewrite /asmmonitor/(.*)$ /asmmonitor/index.php?/$1 last;
    location ^~ /asmmonitor/index.php {
            include /opt/SJRJ/InG/etc/nginx/common/phpfpm_admin.conf;
    }
}

location ^~ /webssh
{
    proxy_pass http://127.0.0.1:8888;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-Host $http_host;

    add_header X-Cache $upstream_cache_status;
    rewrite ^/webssh/(.*) /$1 break;
}