        location ^~ /a/ajax.php {
                if ($arg_tradecode = get_server_time) {
                    add_header Content-Type text/javascript;
                    content_by_lua_block {
                      local time = os.date("%Y-%m-%d %H:%M:%S")
                      ngx.print('__res = "' .. time .. '"')
                    }
                }
                # else
                if ($arg_tradecode != get_server_time) {
                    charset gbk;
                    #include /opt/SJRJ/InG/etc/nginx/module/compatible_ajax.conf;
                    rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                }
               	include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ^~ /a/getotheruser_int.php {
                charset gbk;
               	rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

	location ^~ /a/getotheruser_int/feishu/feishu.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

	location ^~ /a/getotheruser_int/dingtalk/dingtalk.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

	location ^~ /a/getotheruser_int/wework/wework.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ~ /update/upload_file.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ~ /asmtools/qrcode/qrcode.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ^~  /phpdir/trade.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ^~ /phpdir/list/mobile_list.php {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

		location ^~ /backend/api/list {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

		location ^~ /backend/api/resourcesApply {
                charset gbk;
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }

        location ~ /thirdapi/v1/ {
                charset gbk;
                try_files $uri $uri/ /thirdapi/api.php$is_args$args;
        }

        location ^~ /admin {
                charset gbk;
                rewrite ^/admin/(.*)$ https://$host:8443/admin/$1 permanent;
        }
