        location ~ /a/ajax.php {
               	#include /etc/nginx/module/compatible_ajax.conf;
               	rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
               	include /etc/nginx/common/phpfpm.conf;
        }

        location ~ /a/getotheruser_int.php {
               	rewrite ^(.*)$ /access/index.php?rewrite=$1 last;		
                include /etc/nginx/common/phpfpm.conf;
        }

        location ~ /update/upload_file.php {
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /etc/nginx/common/phpfpm.conf;
        }

        location ~ /asmtools/qrcode/qrcode.php {
                rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
                include /etc/nginx/common/phpfpm.conf;
        }

        location ~ /thirdapi/v1/ {
                try_files $uri $uri/ /thirdapi/api.php$is_args$args;
        }
	
        location ^~ /admin {
                rewrite ^/admin/(.*)$ https://$host:10443/admin/$1 permanent;
        }
