location /access/1.0/windows/json/user/qrcode/generate {
    set $tar https://login.dingtalk.com/user/qrcode/generate;
    proxy_pass $tar;
}
location /access/1.0/mac/json/user/qrcode/generate {
    set $tar https://login.dingtalk.com/user/qrcode/generate;
    proxy_pass $tar;
}
location /access/1.0/linux/json/user/qrcode/generate {
    set $tar https://login.dingtalk.com/user/qrcode/generate;
    proxy_pass $tar;
}
location /access/1.0/windows/json/login/login_with_qr {
   set $tar https://login.dingtalk.com/login/login_with_qr;
   proxy_pass $tar;
}
location /access/1.0/mac/json/login/login_with_qr {
     set $tar https://login.dingtalk.com/login/login_with_qr;
     proxy_pass $tar;
}
location /access/1.0/linux/json/login/login_with_qr {
     set $tar https://login.dingtalk.com/login/login_with_qr;
     proxy_pass $tar;
}
location /backend/api/dingtalkUser{
    set $tar https://login.dingtalk.com/user/qrcode/generate;
    proxy_pass $tar;
}
location /backend/api/login/login_with_qr{
    set $tar https://login.dingtalk.com/login/login_with_qr;
    proxy_pass $tar;
}
#location /um {
#    proxy_pass https://g.alicdn.com/security/umscript/3.3.19/um.js;
#}
location /connect {
    set $tar https://oapi.dingtalk.com;
    proxy_pass $tar;
}