set $proxy_feishu_url passport.feishu.cn;
set $sf3_feishu_url sf3-scmcdn-cn.feishucdn.com;
set $proxy_feishu_url_account accounts.feishu.cn;


location /accounts/auth_login/oauth2/authorize{
    proxy_pass https://$proxy_feishu_url_account$request_uri;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}
location /accounts{
    proxy_pass https://$proxy_feishu_url$request_uri;
}
location /suite/passport/oauth/authorize{
    proxy_pass https://$proxy_feishu_url$request_uri;

    proxy_redirect ~^https://accounts.feishu.cn/(.*) ${scheme}://${http_host}/$1;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}
location /suite{
    proxy_pass https://$proxy_feishu_url$request_uri;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}
location = /accounts/auth_login/qr {
    proxy_set_header Accept-Encoding "";
    proxy_pass https://$proxy_feishu_url$request_uri;
    sub_filter 'https://sf3-scmcdn-cn.feishucdn.com' ${scheme}://${http_host};
    sub_filter 'https://sf1-scmcdn-cn.feishucdn.com' ${scheme}://${http_host};

    sub_filter_once off;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}
location ^~ /goofy{
    charset utf-8;
    proxy_pass https://$sf3_feishu_url$request_uri;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}
location ^~ /obj{
    charset utf-8;
    proxy_pass https://$sf3_feishu_url$request_uri;
    access_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/log.lua";
    log_by_lua_file "/opt/SJRJ/InG/usr/local/openresty/lualib/feishu/res_log.lua";
}