location /accounts{
    set $tar https://passport.feishu.cn;
    proxy_pass $tar;
}
location /suite{
    set $tar https://passport.feishu.cn;
    proxy_pass $tar;
}
location = /accounts/auth_login/qr {
    proxy_set_header Accept-Encoding "";
    set $tar https://passport.feishu.cn;
    proxy_pass $tar;
    sub_filter 'https://sf3-scmcdn-cn.feishucdn.com' ${scheme}://${http_host};
    sub_filter_once off;
}
location ^~ /goofy{
    charset utf-8;
    set $tar https://sf3-scmcdn-cn.feishucdn.com;
    proxy_pass $tar;
}