	location ^~  /asm_index_redirect.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /phpdir/include/imgcode.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /asmtools/qrcode/qrcode.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /a/submit.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /a/mobile.php {
        charset gbk;
        include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
    }

	location ^~  /auth_interface.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /asm_proxy/checkDeviceIP.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /a/getotheruser_int/custompage.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /proxy_get_js.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /cutoffnet.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /public.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

    location ~ \.(php)?$ {
        allow 127.0.0.1;
        include /opt/SJRJ/InG/etc/allow.conf;
        deny all;
        include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
        charset gbk;
        expires      30d;
    }

    location ~ .*\.(js|css)?$ {
        charset gbk;
        expires      12h;
    }

    location ~ ^(?!/download/)(.*)\.(tgz|conf)$ {
        charset gbk;
        set $forbid_flag 0;
        if ($remote_addr ~ (127.0.0.1|^191.*)) {
          set $forbid_flag "${forbid_flag}1";
        }
        if ($http_user_agent ~* 'wget') {
          set $forbid_flag "${forbid_flag}1";
        }
        if ($http_referer ~ ^$) {
          set $forbid_flag "${forbid_flag}2";
        }
        if ($forbid_flag = "02") {
          return 404;
        }
    }
