	location ^~  /asm_index_redirect.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	location ^~  /phpdir/trade.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /phpdir/include/imgcode.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /asmtools/qrcode/qrcode.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /a/submit.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ^~  /a/mobile.php {
                charset gbk;
                include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
        }
	
	location ^~  /auth_interface.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
	
	location ^~  /asm_proxy/checkDeviceIP.php {
		charset gbk;
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}
