location /wwopen/sso/v1/qrConnect{
  proxy_set_header Accept-Encoding '';
  set $tar https://open.work.weixin.qq.com;
  proxy_pass $tar;
  sub_filter '//js.aq.qq.com/js' ${scheme}://${http_host};
  sub_filter '//wwcdn.weixin.qq.com' ${scheme}://${http_host};
  sub_filter '//open.work.weixin.qq.com' ${scheme}://${http_host};
  sub_filter_once off;
}
location /wwopen/sso/qrConnect{
    set $tar https://open.work.weixin.qq.com;
    proxy_pass $tar;
}
location ^~ /wwopen/{
    set $tar https://open.work.weixin.qq.com;
    proxy_pass $tar;
}
location = /aq_common.js{
    set $tar https://js.aq.qq.com/js/aq_common.js;
    proxy_pass $tar;
}
location ^~ /node/wwopen/{
    set $tar https://wwcdn.weixin.qq.com;
    proxy_pass $tar;
}
location ^~ /wework2.0.css{
    set $tar https://mdm.infogo.com.cn;
    proxy_pass $tar;
}