location /wwopen/sso/v1/qrConnect{
  access_log /opt/SJRJ/InG/tmp/logs/nginx/wework_access.log;
  error_log /opt/SJRJ/InG/tmp/logs/nginx/wework_error.log notice;

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Accept-Encoding "";

  proxy_cookie_domain .work.weixin.qq.com $host;
  proxy_cookie_domain work.weixin.qq.com $host;
  proxy_cookie_domain .open.work.weixin.qq.com $host;
  proxy_cookie_domain open.work.weixin.qq.com $host;
  proxy_redirect https://open.work.weixin.qq.com/ $scheme://$http_host/;

  add_header X-Debug-Upstream-Status $upstream_status always;
  add_header X-Debug-Upstream-Location $upstream_http_location always;
  add_header X-Debug-Upstream-Set-Cookie $upstream_http_set_cookie always;
  add_header X-Debug-Req-Cookie $http_cookie always;

  sub_filter "//js.aq.qq.com/js" $scheme://$http_host;
  sub_filter "//wwcdn.weixin.qq.com" $scheme://$http_host;
  sub_filter "//open.work.weixin.qq.com" $scheme://$http_host;
  sub_filter_once off;

  set $tar https://open.work.weixin.qq.com;
  proxy_pass $tar;
}
location /wwopen/sso/qrConnect{
  access_log /opt/SJRJ/InG/tmp/logs/nginx/wework_access.log;
  error_log /opt/SJRJ/InG/tmp/logs/nginx/wework_error.log notice;

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_cookie_domain .work.weixin.qq.com $host;
  proxy_cookie_domain work.weixin.qq.com $host;
  proxy_cookie_domain .open.work.weixin.qq.com $host;
  proxy_cookie_domain open.work.weixin.qq.com $host;
  proxy_redirect https://open.work.weixin.qq.com/ $scheme://$http_host/;

  add_header X-Debug-Upstream-Status $upstream_status always;
  add_header X-Debug-Upstream-Location $upstream_http_location always;
  add_header X-Debug-Upstream-Set-Cookie $upstream_http_set_cookie always;
  add_header X-Debug-Req-Cookie $http_cookie always;

  set $tar https://open.work.weixin.qq.com;
  proxy_pass $tar;
}
location ^~ /wwopen/{
  access_log /opt/SJRJ/InG/tmp/logs/nginx/wework_access.log;
  error_log /opt/SJRJ/InG/tmp/logs/nginx/wework_error.log notice;

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_cookie_domain .work.weixin.qq.com $host;
  proxy_cookie_domain work.weixin.qq.com $host;
  proxy_cookie_domain .open.work.weixin.qq.com $host;
  proxy_cookie_domain open.work.weixin.qq.com $host;
  proxy_redirect https://open.work.weixin.qq.com/ $scheme://$http_host/;

  add_header X-Debug-Upstream-Status $upstream_status always;
  add_header X-Debug-Upstream-Location $upstream_http_location always;
  add_header X-Debug-Upstream-Set-Cookie $upstream_http_set_cookie always;
  add_header X-Debug-Req-Cookie $http_cookie always;

  set $tar https://open.work.weixin.qq.com;
  proxy_pass $tar;
}
location = /aq_common.js{
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  set $tar https://js.aq.qq.com/js/aq_common.js;
  proxy_pass $tar;
}
location ^~ /node/wwopen/{
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  set $tar https://wwcdn.weixin.qq.com;
  proxy_pass $tar;
}