    location /ztpwss {
            proxy_pass http://127.0.0.1:20200;
            include /opt/SJRJ/InG/etc/nginx/common/wss.conf;
    }

    # 移动端远程控制客户端连接
    location /remoteMobileWss/client {
            rewrite ^/remoteMobileWss/client/(.*)$ /client/$1 break;
            proxy_pass http://127.0.0.1:16886;
            include /opt/SJRJ/InG/etc/nginx/common/wss.conf;
    }

    # 移动端远程控制管理后台连接
    location /remoteMobileWss/web {
            rewrite ^/remoteMobileWss/web/(.*)$ /web/$1 break;
            proxy_pass http://127.0.0.1:16886;
            include /opt/SJRJ/InG/etc/nginx/common/wss.conf;
    }
