        location /ztpwss {
                proxy_pass http://127.0.0.1:20200;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Real-IP $remote_addr;
                keepalive_timeout 70;
                proxy_connect_timeout 4s;     
                proxy_read_timeout 180s;      
                proxy_send_timeout 12s;
        }
