    location ~ \.(php)?$
    {
        #allow 127.0.0.1;
        #include /opt/SJRJ/InG/etc/allow.conf;
        #deny all;
        fastcgi_index index.php;
        fastcgi_pass   fastcgi_backend;
        fastcgi_keep_conn on;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_ignore_client_abort on;
        include /opt/SJRJ/InG/etc/asm/nginx/*.conf;
        include fastcgi_params;
    }
