		#proxy_pass http://127.0.0.1:9004;
		#include proxy.conf;
		#fastcgi_pass   127.0.0.1:9999;
		#fastcgi_pass unix:/dev/shm/php-fcgi.sock;
		fastcgi_index asm_index_redirect.php;
		fastcgi_pass fastcgi_frontend;
		fastcgi_keep_conn on;
		fastcgi_param  DOCUMENT_ROOT      $document_root;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_ignore_client_abort on;
		include /etc/asm/nginx/*.conf;
		include fastcgi_params;
