		fastcgi_index index.php;
        fastcgi_pass fastcgi_backend;
        fastcgi_keep_conn on;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_ignore_client_abort on;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 1800;
        fastcgi_read_timeout 1800;
        include /opt/SJRJ/InG/etc/asm/nginx/*.conf;
        include fastcgi_params;
