		#proxy_connect_timeout 60s;
		#proxy_read_timeout 600s;
		#proxy_send_timeout 600s;
		#include proxy.conf;
		#fastcgi_pass   127.0.0.1:9999;
		#fastcgi_pass   unix:/dev/shm/php-fcgi.sock;
		fastcgi_index index.php;
		fastcgi_pass fastcgi_backend;
		fastcgi_keep_conn on;
		fastcgi_param  DOCUMENT_ROOT      $document_root;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_ignore_client_abort on;
		fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
		include /etc/asm/nginx/*.conf;
		include fastcgi_params;