        ssl_protocols TLSv1.2 TLSv1.3;
        # use pm
        ssl_certificate         /opt/SJRJ/InG/etc/pki/tls/certs/localhost.crt;
        ssl_certificate_key     /opt/SJRJ/InG/etc/pki/tls/private/localhost.key;
