upstream eventbroker {
    server [::1]:50001;
	keepalive 300;
}

upstream nacservice {
	server [::1]:50002;
	keepalive 300;
}

upstream sceneservice {
	server [::1]:50003;
	keepalive 300;
}

server {
    listen    50000 ssl;
    listen    [::]:50000 ssl;
    http2 on;

    server_name    localhost;

    # It is valid for 30 years and can be regenerated or renewed by October 2052 under normal conditions
    ssl_certificate        /opt/SJRJ/InG/etc/pki/tls/certs/grpc.crt;
    ssl_certificate_key    /opt/SJRJ/InG/etc/pki/tls/private/grpc.key;
    ssl_protocols          TLSv1.2 TLSv1.3;
    ssl_ciphers            HIGH:!aNULL:!MD5:!kRSA;
    ssl_prefer_server_ciphers on;

	# http://nginx.org/en/docs/http/ngx_http_grpc_module.html
    grpc_read_timeout 365d;
    grpc_send_timeout 365d;
    grpc_socket_keepalive on;

    location /srv.eventbroker {
        grpc_pass grpc://eventbroker;
    }
    location /srv.nacservice {
        grpc_pass grpc://nacservice;
    }
    location /srv.sceneservice {
        grpc_pass grpc://sceneservice;
    }

}
