
upstream fastcgi_frontend {
    server 127.0.0.1:9999;
    #server unix:/dev/shm/php-fcgi.sock;
    keepalive 8;
}

server {
	listen 80;
	listen  [::]:80;
	ssi on;
	server_name localhost;
	root /opt/SJRJ/InG/var/www/html;
	index asm_index_redirect.php index.php index.html index.htm;
	charset gbk;
	client_body_temp_path  /opt/SJRJ/InG/tmp/logs/nginx 1 2;
	error_page 404  =200 /;
	location ^~ /access/ui {
		rewrite ^(.*) https://$host/admin break;
	}

	location ~ /a/(index.html|auth.html) {
		 rewrite ^(.*) https://$host/admin break;
	
	}
	location ~ /a2/(index.html|auth.html) {
		 rewrite ^(.*) https://$host/admin break;
	
	}
	location ~ /a/mobile/(.*) {
		rewrite ^(.*) https://$host/admin break;
	}
	location ~ /a2/mobile/(.*) {
		rewrite ^(.*) https://$host/admin break;
	}
	

	location ^~ /access {
		set $is_exist_filename 1;
		
		if ($request_uri ~* "infoprocess|auth") {
			rewrite ^(.*) https://$host/admin break;
		}
		if ($request_filename != '/opt/SJRJ/InG/var/www/html/access/index.php') {
			set $is_exist_filename 0;
			rewrite ^(.*)$ /access/index.php?rewrite=$1 last;
		}
		# else
		if ($is_exist_filename = 1) {
			root /opt/SJRJ/InG/var/www/access.asm.com/webroot;
		}
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ~ /download/getip.php{
		echo IP:$remote_addr;
		break;
	}

	location ^~ /vendor {
                deny all;
                return 403;
        }

	location ~* /composer\.(json|lock)$ {
			deny all;
			return 403;
	}
	
	include /opt/SJRJ/InG/etc/nginx/module/compatible.conf;

	location ~ \.(php)?$ {
		include /opt/SJRJ/InG/etc/nginx/common/phpfpm.conf;
	}

	location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
		expires      30d;
	}

	location ~ .*\.(js|css)?$ {
		expires      12h;
	}
	location ~ .*\.(tgz|conf|rar)$ {
		set $forbid_flag 0;
		if ($remote_addr ~ (127.0.0.1|^191.*)) {
			set $forbid_flag "${forbid_flag}1";
		}
		if ($http_user_agent ~* 'wget') {
			set $forbid_flag "${forbid_flag}1";
		}
		if ($http_referer ~ ^$) {
			set $forbid_flag "${forbid_flag}2";
		}
		if ($request_uri ~* "/download/patchupdate.rar") {
			set $forbid_flag "${forbid_flag}3";
		}
		if ($forbid_flag = "02") {
			return 404;
		}
	}

}
