
upstream fastcgi_frontend {
    server 127.0.0.1:9999;
    #server unix:/dev/shm/php-fcgi.sock;
    keepalive 8;
}

server {
	listen 80;
	listen  [::]:80;
	ssi on;
	server_name localhost;
	root /opt/SJRJ/InG/var/www/html;
	index asm_index_redirect.php index.php index.html index.htm;
	charset gbk;
	client_body_temp_path  /opt/SJRJ/InG/tmp/logs/nginx 1 2;
	error_page 404  =200 /;

	include /opt/SJRJ/InG/etc/nginx/module/access_dasm.conf;
	include /opt/SJRJ/InG/etc/nginx/module/compatible.conf;
}
