server {
    listen       [fec0:ffff::1]:44347 ssl;
    server_name  localhost;

    charset gbk;
    #ssl                  on;
    ssl_certificate      /opt/SJRJ/InG/etc/pki/tls/certs/localhost.crt;
    ssl_certificate_key  /opt/SJRJ/InG/etc/pki/tls/private/localhost.key;
    ssl_dhparam /opt/SJRJ/InG/etc/pki/tls/certs/dhparams.pem;

    root /opt/SJRJ/InG/var/www/html;
    index redirect_ipv6.php;
    error_page 404  /redirect_ipv6.php;
    error_page 403  /redirect_ipv6.php;
    ssl_session_timeout  5m;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers   on;

    include /opt/SJRJ/InG/etc/nginx/common/phpfpm_limit_phpfile.conf;
}
